### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by AlexaNm76** [Archie3d/aeolus_plugin#10]
First of all, thank you so much for saving such a useful piece of software from abandonment!
I am a Mac user, and I found the pipe chiff a bit annoying ... I think it would be important to be able to adjust its volume.
I don't remember if it was there in Fons Adriansen's original, in the settings page that has not yet been ported to your new version ... I hope you will!
Best Regards
Alex

**Comment by Archie3d** [comment]
Hi, the original Fons' implementation does not have any chiff modelling indeed, I had to add it. I don't think I will be adding an extensive configuration UI for all the aspects of the organ, but you can already adjust all of these actually.

So, the chief volume is configured per stop, and it's defined in the [organ config file](https://github.com/Archie3d/aeolus_plugin/blob/master/Resources/configs/default_organ.json) that is by default embedded into the application. There is a possibility to use a custom organ config file. To do this you have to take the default file I've just mentioned and rename it to `organ_config.json`. Now you can edit this file as you like - adding, removing manuals, stops, changing mixtures, and adjusting volumes.
Next, you have to place the edited `organ_config.json` to the "working directory" from where you launch the application or where the plug-in gets loaded from.

Now, I don't know whether you use Aeolus as a stand-alone or as a plugins, but assuming it's a stand-alone `Aeolus.app` you launch, you have to place the `organ_config.json` into the root directory on your Mac (that is normally `Macintosh HD` from finder, or `/` from a terminal). After that restarting `Aeolus.app` will pick your custom configuration instead of the default embedded one. This will let you to turn down the chiff volume as you like.

I should probably move the custom configuration elsewhere to user friendlier place (like Documents folder). Will update on this in the new version.

Hope this helps.

**Comment by AlexaNm76** [comment]
Hi Arthur, actually I hardly remember the old interface, it had a volume control panel, a midi panel and nothing more.
But the configuration file you pointed me to is most useful and I think it solves my query. (Yes, I use it standalone).
Thank you!
Alex

**Comment by Synthematophon** [comment]
Hi Arthur, is there also a possibiliy (via the organ_config.json file) to change to change the original embedded (?) wavetable-file (*,aeO)?
Thanks
Synthematophon

**Comment by Archie3d** [comment]
Hi @Synthematophon, currently only the embedded pipes can be referenced from the external config file indeed. I'll update the plugin to let it load external pipes and will make a new build.

**Comment by Synthematophon** [comment]
Wow Arthur, so fast reply. Thanks a lot!

 
 

Gesendet: Mittwoch, 25. Januar 2023 um 15:39 Uhr
Von: "Arthur Benilov" ***@***.***>
An: "Archie3d/aeolus_plugin" ***@***.***>
Cc: "Synthematophon" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Archie3d/aeolus_plugin] Settings (Issue #10)


 

Hi @Synthematophon, currently only the embedded pipes can be referenced from the external config file indeed. I'll update the plugin to let it load external pipes and will make a new build.

**Comment by Archie3d** [comment]
@Synthematophon , please check the `0.1.13` release here: https://github.com/Archie3d/aeolus_plugin/releases/tag/v0.1.13
This should allow you using your custom pipes from the custom organ config.

**Comment by Synthematophon** [comment]
Great job! It's working! Thank you so much!
