### ISSUE TITLE
Linux binaries or instructions on how to build?

### ISSUE THREAD

**Issue by ElizabethHarmon** [Archie3d/aeolus_plugin#11]
It would be great to have native Linux standalone and plugins as part of the releases. If not, would you be kind enough to provide instructions on how to build?

**Comment by Archie3d** [comment]
Hi, providing Linux binaries is troublesome since it depends on a particular runtime and Linux flavour, and there are a lot.  Compiling it though is very easy (I'm already doing this via [GitHub action here](https://github.com/Archie3d/aeolus_plugin/blob/master/.github/workflows/build.yml)).

E.g. on Debian-like:
```shell
sudo apt update
sudo apt install build-essential ninja-build g++
sudo apt install libx11-dev libfreetype-dev libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev
cd ~/aeolus_plugin # <--- This is where the repo was cloned to
mkdir -p build
cd build
cmake ../ -D WITH_ASIO=OFF -D CMAKE_BUILD_TYPE=Release
cmake --build .
```

**Comment by ElizabethHarmon** [comment]
Thanks!
