### ISSUE TITLE
Stop "Sesquialtera II"

### ISSUE THREAD

**Issue by Victor-Ch** [Archie3d/aeolus_plugin#20]
Using default configuration, the stop "Sesquialtera II" (Manual I) produces only 1 voice per any one pressed key.
The default config of the stop is:
{ "name": "Sesquialtera\nII",         "type": "principal",    "pipe": "sesqualtera",      "chiff": 0.17, "gain": 3.0 }

But according to its name, it should connect 2 pipes and should produce two-voice sounds (at least).
Comment on that, please.

**Comment by Archie3d** [comment]
The original Aeolus did not have an option to construct a proper mixtures by combining multiple pipes. Instead it combined all the harmonics of the mixture into a single pipe definition. This particular stop is an example of that original approach, which is why it produces only one voice (two pipes harmonics are combined into one). In my implementation I've split more complex mixtures to make them be properly defined by combining multiple pipes (which also allowed mixtures breaking-back - using different pipes within a single stop depending on the keys rage position).
Hope this explains your observation.

**Comment by Victor-Ch** [comment]
Yes, this explains everything.
It's that voice meter on the top left of the window - it kind of confuses displaying "1" for the stop.

**Comment by Archie3d** [comment]
Right. That is kind of an instrumental (as an engineering term) meter showing the number of pipe models being currently voiced. Some pipes may indeed produce multiple voices. The total number or simultaneously played voices is currently limited to 256.
