### ISSUE TITLE
AUv3 build for iPad?

### ISSUE THREAD

**Issue by xhub** [Archie3d/aeolus_plugin#27]
Very nice work on the aeolus plugin.

Have you considered making an AUv3 plugin version of it? Or a standalone iPadOS version?

I believe JUCE already supports AUv3.

**Comment by Archie3d** [comment]
Hi, thanks! No, I have not considered an AUv3 plugin, since this would require me to be involved with Apple's signing, notarization, and distribution ecosystem, and keep a dev account.
The standalone plugin though should compile and run fine on iPad, so you should be able to perform an ad-hoc installation.

**Comment by xhub** [comment]
I understand. I just got an iPad coming form Linux/Android and the walled aspect is tough.

I may try to play with this during the holiday and use AltStore. Sideloading seems possible with 17.2 in the EU.

**Comment by lewisalexander2020** [comment]
if this could be compiled for the ipad, this would be an interesting test. yes, there would be problems if it went as an official apple store release due to a number of legal issues, but from a software perspective if the legal matters weren’t a problem, then great. There’s nothing wrong with having an apple developer account, etc, been there for several years but wound down from any development work / consultation work as of this year, so no longer take developer projects, unless it’s a company I’m still connected with, only then  do I provide any developer work, but I’m now technically retired from it all, phew.

Aeolus on a 12.9” ipad pro would be something interesting. if this does go ahead as a third party install, could you keep me posted please.

yes, JUCE does support AUV3, in fact JUCE is a great developer tool for music applications including implementing accessibility in to music apps.

lew
