### ISSUE TITLE
Allow multiple MIDI channels to be selected

### ISSUE THREAD

**Issue by Archie3d** [Archie3d/aeolus_plugin#30]
Currently the drop-down selection allows `All` or a single discrete channel to be selected. It should be possible to select multiple discrete MIDI channels.

From @Synthematophon https://github.com/Archie3d/aeolus_plugin/issues/18#issuecomment-2159932911
> Hi, another question since my console sends the sequencer steps via MIDI channel 8 you implemented a controller dropdown list for choosing the channel. Actually i have additionally foot-piston which are unfortunately sending at channel 7. You were so kind to implement the issue with different notes for the sequencer. Would it be possible to choose different channels (beside to choose "all" in the dropdown list) for example via checkboxes?
> Thanks a lot!

**Comment by Archie3d** [comment]
@Synthematophon This should be in [develop](https://github.com/Archie3d/aeolus_plugin/tree/develop) branch now.
This allows assigning any MIDI channels to divisions and controls. Could you please check and let me know whether this works for you?

**Comment by Synthematophon** [comment]
Thanks so much. "Unfortunately" i actually are in holiday and my console is hundred km away. If you couldnt wait one week i will informe you immediately after return. Kind regards --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 16.06.24, 12:05 schrieb Arthur Benilov ***@***.***>:

   
  @Synthematophon This should be in develop branch now. This allows assigning any MIDI channels to divisions and controls. Could you please check and let me know whether this works for you?

**Comment by Archie3d** [comment]
@Synthematophon No worries, this is not urgent at all. Enjoy your holidays!

**Comment by Synthematophon** [comment]
Hi,

i had now the opportunity to test the new application.

It looks really good. And it's working almost perfect.

For some strange reasons the sequencer now is reacting to not on signals coming from the deepes midi-notes.

So far i understand exactly this behaviour is normaly exluded in the code (engine.cpp). I have the impression that on midi chanel 1 the sequncer is reacting to notes events although my console sends the sequencer steps on channel 7 and 8.

Maybe it's also my mistake, because I didn't take over the files completely during the compilation, but only the changed parts. I also adapted some things (such as IRS) myself (engine.cpp). Maybe I just forgot something during the transfer. I will try again and report back tomorrow.
In the meantime, thank you very much for your great effort!

 

Kind regards

Synthematophon

 

 

 
 

Gesendet: Sonntag, 16. Juni 2024 um 12:05 Uhr
Von: "Arthur Benilov" ***@***.***>
An: "Archie3d/aeolus_plugin" ***@***.***>
Cc: "Synthematophon" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Archie3d/aeolus_plugin] Allow multiple MIDI channels to be selected (Issue #30)


 

@Synthematophon This should be in develop branch now.
This allows assigning any MIDI channels to divisions and controls. Could you please check and let me know whether this works for you?

**Comment by Archie3d** [comment]
Hi @Synthematophon
thank you for testing. I found indeed some problems and pushed the fix. Please pull the latest develop branch once you get to this again.

Also, it might be more convenient for you to keep your private changes on a separate git branch, this way you can just merge the upstream changes (develop) into your branch and don't need to look for all the modified code parts.

**Comment by Synthematophon** [comment]
Great! Now everything works exactly as it should.

Thanks so much.

You are a hero!

 

 
 

Gesendet: Dienstag, 25. Juni 2024 um 11:40 Uhr
Von: "Arthur Benilov" ***@***.***>
An: "Archie3d/aeolus_plugin" ***@***.***>
Cc: "Synthematophon" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Archie3d/aeolus_plugin] Allow multiple MIDI channels to be selected (Issue #30)


 

Hi @Synthematophon
thank you for testing. I found indeed some problems and pushed the fix. Please pull the latest develop branch once you get to this again.

Also, it might be more convenient for you to keep your private changes on a separate git branch, this way you can just merge the upstream changes (develop) into your branch and don't need to look for all the modified code parts.
