### ISSUE TITLE
Differing name?

### ISSUE THREAD

**Issue by mxmilkiib** [Archie3d/aeolus_plugin#6]
Hello. Given the fork is going in a new direction, might I suggest giving it a new name? I think the same issue has arisen previously, and Fons wasn't too keen on the confusion it created.

**Comment by Archie3d** [comment]
Hi. Well, I am not sure. Keeping the original name in some form is a tribute to the original project actually, and also due to the fact that the original additive synthesis model gets reused here. Since the original project has never offered an audio plugin interafce I think stressing the `plugin` here should help avoiding any confusion.

I'd need to gather more feedback, then I may reconsider the naming. Meanwhile will leave this issue open for people to pitch in.

**Comment by mxmilkiib** [comment]
Okies. Some reference; http://lalists.stanford.edu/lad/2013/09/index.html#29 though probably best to contact Fons directly

**Comment by rmattes** [comment]
Since you aked for feeback: I'm with [mxmilkiib](https://github.com/mxmilkiib) here. Please rename the project. Otherwise it might look loke a hostile takeover of the project (which, in my understanding, it isn't). Having different software under the same name is a nightmare for both maintainers (bug reports concerning the "other" version) as well as distributions.

**Comment by ElizabethHarmon** [comment]
I think renaming is completely unnecessary...aeolus-plugin is fine. I find Fons is overly protective with his stuff. Perhaps he should have released closed source if he wasn't willing for people to legally use his open-source code? Call it aeolus+ or whatever. It's your baby and for what it's worth, it's amazing and a great improvement.

**Comment by falkTX** [comment]
a bump for another "please rename the project" request.
Fons (aeolus original author) already had to deal with people taking his stuff and making unofficial versions without renaming anything, then people mailing him about support for something he has no participation in.

Last time I mentioned likely stopping opensource development altogether due to this lack of respect of one's authorship. Let's not make it worse please.

**Comment by rmattes** [comment]
Yet another bump for the rename. This is neither a true fork nor a continued development, you just ripped selective parts from the original project. To be blunt: after listening to the plugin version I can very well understand why Fons does not want to be related to this.

**Comment by Archie3d** [comment]
Do you mind guys providing me with some information on how exactly you use this project? Thanks!

**Comment by lewisalexander2020** [comment]
I was in the process of adopting this in to an accessible organ build system as a blind organist and developer, but a number of factors have stopped me from this.

1: lack of expansion / support for particular stops / stop galleries.
2: Current stop specification does not give the realism of a pipe organ.
3: lack of suitable 16’ stops throughout. it feels like the console experience is limited and sounds significantly different to aeolus itself.

I’m sadly no longer using this app as my work is committed to two major developers, one of which respects my time, experience and background to the point of completion by the end of the year.

I’m also heavily committed on a physical console build from scratch which is 3/4 way through the build process.

lew

**Comment by Archie3d** [comment]
Thank you for all the feedback, much appreciated.

It seems to me that people advocating for the name change have no use or any stake in this project. I don’t think the naming causes any confusion or misrepresentation. I don’t try to capitalize on Aeolus name or steal someone’s fame or anything. The licencing terms are respected, the credit is given where the credit is due, all information and the links are clearly provided in the project description. The project has been referenced in various places across the web now, and changing the name and the repo is simply not practical at this point. I’ve been in touch with several organists who actually appreciated the naming similarity since this allowed them to discover the plugin and relate it to the original Aeolus. Some of them actually use both – the plugin and the original Linux one, they’ve expressed no confusion whatsoever, and seem to be quite happy with the fact they could seamlessly transfer the pipe definitions (*.ae0 files) and use them in the plugin (since the wave tables generation part is identical).

I want to stress once again, the main goal of this project is to provide a VST/AU plugin that runs on Windows and macOS systems. Stand-alone executables and Linux builds are just a side effects of the tools being used. Linux support was never my priority, but obviously I am happy for people to use this on Linux if they want to.

Considering all this, I’ve decided to politely ignore this request and keep the initial name – aeolus_plugin.

**Comment by Archie3d** [comment]
This issue will be closed now.
