### ISSUE TITLE
Program Change in Cakewalk

### ISSUE THREAD

**Issue by BobOmellette** [Archie3d/aeolus_plugin#9]
I'm unclear on how to set/change the registration during a MIDI playback.  I use Cakewalk, but can't seem to get it to recognize any Program change event.

It is probable that I'm doing it incorrectly.  I've attempted to use the Bank/Patch change dropdowns on one of the MIDI controller tracks (I have each manual controlled by a separate MIDI track), and I've tried sending a value via CC0 -- neither seems to work.

Perhaps it would help if there's more clear documentation on how to perform registration changes during playback?  Ideally, we should be able to toggle each individual stop in real-time, but I'll take just being able to choose between the 16 registration changes.

**Comment by Archie3d** [comment]
Hi, this problem is actually related to how VTS3 differs from VST. VST3 plugin does not pass through program change MIDI events for some reason, but instead it exposes a "Program" parameter that you can automate.

So there are two solutions for this:
- Use VST version of the plugin (instead of VST3);
- Use "Program" parameter automation to change the sequencer position when using VST3 plugin.

Hope this helps. I'll update the readme.

P.S. CC for individual stops is on my todo list. But for now the only way is to use the sequencer.
